### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by ralyodio** [remixz/to-streamable#1]
```
$ to-streamable video.mp4 --auth=foo:bar
Uploading...
/Users/username/.nvm/versions/node/v6.6.0/lib/node_modules/to-streamable/out/index.js:17
function _slicedToArray(arr, i) { if (Array.isArray(arr)) { return arr; } else if (Symbol.iterator in Object(arr)) { var _arr = []; var _n = true; var _d = false; var _e = undefined; try { for (var _i = arr[Symbol.iterator](), _s; !(_n = (_s = _i.next()).done); _n = true) { _arr.push(_s.value); if (i && _arr.length === i) break; } } catch (err) { _d = true; _e = err; } finally { try { if (!_n && _i['return']) _i['return'](); } finally { if (_d) throw _e; } } return _arr; } else { throw new TypeError('Invalid attempt to destructure non-iterable instance'); } }


TypeError: Invalid attempt to destructure non-iterable instance
    at _slicedToArray (/Users/username/.nvm/versions/node/v6.6.0/lib/node_modules/to-streamable/out/index.js:17:492)
    at Request._callback (/Users/username/.nvm/versions/node/v6.6.0/lib/node_modules/to-streamable/out/index.js:64:21)
    at Request.self.callback (/Users/username/.nvm/versions/node/v6.6.0/lib/node_modules/to-streamable/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/username/.nvm/versions/node/v6.6.0/lib/node_modules/to-streamable/node_modules/request/request.js:1060:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/username/.nvm/versions/node/v6.6.0/lib/node_modules/to-streamable/node_modules/request/request.js:980:12)
    at IncomingMessage.g (events.js:291:16)
```

**Comment by Michael-Cooper** [comment]
I'm getting the same issue.  The upload is going through to Streamable, but then I get this error and miss out on the returned shortcode.

I understand this could be happening because I'm dumb.

**Comment by ralyodio** [comment]
I don't think its you. I rebuilt the library and am still seeing it. I believe OP is using an old version of babel.

I will contact streamable.com as they list this module on their tools page but it seems dead and does not work. Maybe they can have someone fork it and fix it.

I opened this issue in October and emailed the dev directly. Have not heard anything.

**Comment by remixz** [comment]
I've just updated the module to `2.0.0`, which fixes this bug. I've bumped it to a major version as I'm now requiring Node 6+, so that we don't need the compilation step. The API itself stays the same though. Cheers!

**Comment by ralyodio** [comment]
Awesome @remixz thank you!
