### ISSUE TITLE
new error with v2

### ISSUE THREAD

**Issue by ralyodio** [remixz/to-streamable#2]
$ to-streamable video.mp4
	Uploading...
	/Users/username/.nvm/versions/node/v7.3.0/lib/node_modules/to-streamable/src/index.js:32
	      const { shortcode } = body
	                            ^

	TypeError: Cannot match against 'undefined' or 'null'.
	    at Request.request [as _callback] (/Users/username/.nvm/versions/node/v7.3.0/lib/node_modules/to-streamable/src/index.js:32:29)
	    at self.callback (/Users/username/.nvm/versions/node/v7.3.0/lib/node_modules/to-streamable/node_modules/request/request.js:186:22)
	    at emitOne (events.js:101:20)
	    at Request.emit (events.js:188:7)
	    at FormData.<anonymous> (/Users/username/.nvm/versions/node/v7.3.0/lib/node_modules/to-streamable/node_modules/request/request.js:1182:10)
	    at emitOne (events.js:101:20)
	    at FormData.emit (events.js:188:7)
	    at FormData.CombinedStream._emitError (/Users/username/.nvm/versions/node/v7.3.0/lib/node_modules/to-streamable/node_modules/combined-stream/lib/combined_stream.js:187:8)
	    at DelayedStream.<anonymous> (/Users/username/.nvm/versions/node/v7.3.0/lib/node_modules/to-streamable/node_modules/combined-stream/lib/combined_stream.js:113:10)
	    at emitOne (events.js:101:20)

npm info:

	 
	{ name: 'to-streamable',
	  description: 'Upload video quickly to Streamable.com',
	  'dist-tags': { latest: '2.0.0' },
	  versions: [ '1.0.0', '1.1.0', '1.1.1', '1.2.0', '1.2.1', '2.0.0' ],
	  maintainers: [ 'remixz <mail@bruggie.com>' ],
	  time: 
	   { modified: '2017-01-23T22:34:38.807Z',
	     created: '2015-05-31T02:56:49.695Z',
	     '1.0.0': '2015-05-31T02:56:49.695Z',
	     '1.1.0': '2015-05-31T08:23:40.073Z',
	     '1.1.1': '2015-05-31T08:40:32.721Z',
	     '1.2.0': '2015-05-31T20:10:21.108Z',
	     '1.2.1': '2015-05-31T20:26:52.214Z',
	     '2.0.0': '2017-01-23T22:34:38.807Z' },
	  homepage: 'https://github.com/remixz/to-streamable#readme',
	  keywords: [ 'upload', 'streamable.com', 'video', 'cli' ],
	  repository: 
	   { type: 'git',
	     url: 'git+https://github.com/remixz/to-streamable.git' },
	  author: 'Zach Bruggeman <mail@bruggie.com>',
	  bugs: { url: 'https://github.com/remixz/to-streamable/issues' },
	  license: 'MIT',
	  readmeFilename: 'README.md',
	  users: { jerkovicl: true },
	  version: '2.0.0',
	  main: 'src/index.js',
	  bin: { 'to-streamable': 'src/bin.js' },
	  scripts: { test: 'standard src/*.js && tap test/*.js' },
	  dependencies: 
	   { 'application-config': '^1.0.1',
	     'concat-stream': '^1.6.0',
	     'file-type': '^4.1.0',
	     minimist: '^1.2.0',
	     prompt: '^1.0.0',
	     request: '^2.79.0' },
	  devDependencies: { standard: '^8.6.0', tap: '^9.0.3' },
	  gitHead: 'f1d4a1812de8d5402c015540ac5257d334627630',
	  dist: 
	   { shasum: '5b9ffea5ead54fb5e11c847a10d6d952e6dd2ce9',
	     tarball: 'https://registry.npmjs.org/to-streamable/-/to-streamable-2.0.0.tgz' },
	  directories: {} }

**Comment by ralyodio** [comment]
It appears --setup doesn't work but using --auth=user:pass does.

**Comment by EzequielDM** [comment]
The same is happening to me
